site_name: Cosys-AirSim
repo_url: https://github.com/Cosys-Lab/Cosys-AirSim
site_description: 'Cosys-AirSim is a simulator for drones, cars and more, built on Unreal Engine. We expand it with new implementations and sensor modalities.'

theme: readthedocs

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

edit_uri: https://github.com/Cosys-Lab/Cosys-AirSim/edit/main/docs/

nav:
  - "Home":
    - "Home": 'README.md'
  - "Changelog": 'https://github.com/Cosys-Lab/Cosys-AirSim/blob/main/CHANGELOG.md'
  - "Installing AirSim":
    - "Download and run": 'run_packaged.md'
    - "Download and install from precompiled plugin": 'install_precompiled.md'
    - "Install from Source on Windows": 'install_windows.md'
    - "Install from Source on Linux": 'install_linux.md'
    - "Using Docker on Ubuntu": 'docker_ubuntu.md'
    - "Custom Unreal Environment": 'unreal_custenv.md'
    - "Dynamic Objects": 'dynamic_objects.md'
  - "Using AirSim":
    - "Core APIs": 'apis.md'
    - "Image APIs": 'image_apis.md'
    - "C++ APIs": 'apis_cpp.md'
    - "Instance Segmentation": 'instance_segmentation.md'
    - "Annotation": 'annotation.md'
    - "Settings": 'settings.md'
    - "Camera Views": 'camera_views.md'
    - "Car Mode": 'using_car.md'
    - "Remote Control": 'remote_control.md'
    - "XBox Controller": 'xbox_controller.md'
    - "Steering Wheel": 'steering_wheel_installation.md'
    - "Multiple Vehicles": 'multi_vehicle.md'
    - "Skid Steer Vehicles": 'skid_steer_vehicle.md'
    - "Import Gazebo models": "gazebo_drone.md"
    - "Domain Randomization": "retexturing.md"
    - "Mesh Vertex Buffers": "meshes.md"
    - "Artificial Lights": 'lights.md'
    - "Sensors":
      - "Sensors": 'sensors.md'
      - "LIDAR": 'lidar.md'
      - "GPU LIDAR": 'gpulidar.md'
      - "Pulse Echo": 'echo.md'
      - "Infrared Camera": "InfraredCamera.md"
      - "Distance Sensor": 'distance_sensor.md'
    - "ROS":
      - "ROS: AirSim ROS Python Wrapper": "ros_python.md"
      - "ROS2: AirSim ROS C++ Wrapper": "ros_cplusplus.md"
    - "Matlab": 'matlab.md'
    - "Playing Logs": 'playback.md'
    - "Voxel Grid Generator": "voxel_grid.md"
    - "Event camera": "event_sim.md"
  - "Design":
    - "Modifying Recording Data": 'modify_recording_data.md'
    - "Flight Controller": 'flight_controller.md'
    - "Adding new APIs": 'adding_new_apis.md'
    - "Simple Flight": 'simple_flight.md'
  - "External Flight Controllers":
    - "MavLink and PX4":
      - "PX4 Setup for AirSim": 'px4_setup.md'
      - "PX4 in SITL": 'px4_sitl.md'
      - "PX4 SITL with WSL 2": 'px4_sitl_wsl2.md'
      - "PX4 Lockstep": 'px4_lockstep.md'
      - "PX4 Multi-vehicle in SITL": 'px4_multi_vehicle.md'
      - "AirSim with Pixhawk": 'https://youtu.be/1oY8Qu5maQQ'
      - "PX4 Setup with AirSim": 'https://youtu.be/HNWdYrtw3f0'
      - "Debugging Attitude Estimation": 'https://www.youtube.com/watch?v=d_FyjKDWQfc&feature=youtu.be'
      - "Intercepting MavLink Messages": 'https://github.com/Microsoft/AirSim/wiki/Intercepting-MavLink-messages'
      - "Rapid Descent on PX4 Drones": 'https://github.com/Microsoft/AirSim/wiki/Rapid-Descent-on-PX4-drones'
      - "Building PX4": "px4_build.md"
      - "PX4/MavLink Logging": 'px4_logging.md'
      - "MavLink LogViewer": "log_viewer.md"
      - "MavLinkCom": 'mavlinkcom.md'
      - "MavLink MoCap": 'mavlinkcom_mocap.md'
    - "ArduPilot":
      - "ArduPilot SITL Setup": "https://ardupilot.org/dev/docs/building-the-code.html"
      - "AirSim & ArduPilot": "https://ardupilot.org/dev/docs/sitl-with-airsim.html"
  - "Contributed Tutorials":
    - "Using Environments from Marketplace": 'https://www.youtube.com/watch?v=y09VbdQWvQY'
    - "Simple Collision Avoidance": 'https://github.com/simondlevy/AirSimTensorFlow'
    - "Autonomous Driving on Azure": 'https://aka.ms/AutonomousDrivingCookbook'
    - "Building Hexacopter": 'https://github.com/Microsoft/AirSim/wiki/hexacopter'
    - "Moving on Path Demo": 'https://github.com/Microsoft/AirSim/wiki/moveOnPath-demo'
    - "Importing a custom multirotor mesh": 'https://youtu.be/Bp86WiLUC80'
    - "Object Detection": "object_detection.md"
    - "AirSim with MAVROS and PX4": 'https://youtu.be/ZonkdMcwXH4'
  - "Misc":
    - "AirSim on Real Drones": 'custom_drone.md'
    - "Installing cmake on Linux": 'cmake_linux.md'
    - "pfm format": 'pfm.md'
    - "Setting up Unreal Environment": 'unreal_proj.md'
    - "Building and Packaging Cosys-AirSim Plugin and/or Unreal Projects": 'packaging.md'
    - "Blocks Environment": 'unreal_blocks.md'
    - "Working with UE Plugin Contents": 'working_with_plugin_contents.md'
    - "Formula Student Technion Self-drive": 'https://github.com/Microsoft/AirSim/wiki/technion'